---
# tasks file for centos-update

- name: Ensure deltarpm installed (before updating CentOS packages)
  yum: name=deltarpm state=latest

- name: Update CentOS packages
  yum: name=* state=latest update_cache=yes

- name: Ensure EPEL installed
  yum: name=epel-release state=latest

- name: Ensure basic sysadmin tools installed
  yum: name={{ item }} state=latest
  with_items: "{{ sysadmin_tools }}"
